<?php
/**
 * MUFiles.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUFiles
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * Generic item list block implementation class.
 */
class MUFiles_Block_ItemList extends MUFiles_Block_Base_ItemList
{
    /**
     * Determines the order by parameter for item selection.
     *
     * @param array               $vars       List of block variables.
     * @param Doctrine_Repository $repository The repository used for data fetching.
     *
     * @return string the sorting clause.
     */
    protected function getSortParam($vars, $repository)
    {
        if ($vars['sorting'] == 'random') {
            return 'RAND()';
        }
    
        $sortParam = '';
        if ($vars['sorting'] == 'newest') {
            $idFields = ModUtil::apiFunc('MUFiles', 'selection', 'getIdFields', array('ot' => $vars['objectType']));
            if (count($idFields) == 1) {
                $sortParam = $idFields[0] . ' DESC';
            } else {
                foreach ($idFields as $idField) {
                    if (!empty($sortParam)) {
                        $sortParam .= ', ';
                    }
                    $sortParam .= $idField . ' DESC';
                }
            }
        } 
        
        if ($vars['sorting'] == 'updated') {
        	$sortParam = 'updatedDate DESC';
        }
        if ($vars['sorting'] == 'default') {
            $sortParam = $repository->getDefaultSortingField() . ' ASC';
        }
    
        return $sortParam;
    }
}
