<?php
/**
 * Files.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\FilesModule;

use MU\FilesModule\Base\AbstractFilesModuleInstaller;

/**
 * Installer implementation class.
 */
class FilesModuleInstaller extends AbstractFilesModuleInstaller
{
    // feel free to extend the installer here
}
