<?php
/**
 * MUFiles.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUFiles
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * Notify operation.
 * @param object $entity The treated object.
 * @param array  $params Additional arguments.
 *
 * @return bool False on failure or true if everything worked well.
 */
function MUFiles_operation_notify(&$entity, $params)
{
    $dom = ZLanguage::getModuleDomain('MUFiles');


    // initialise the result flag
    $result = false;

    $notifyArgs = array(
        'recipientType' => $params['recipientType'],
        'action' => $params['action'],
        'entity' => $entity
    );
    
    ModUtil::apiFunc('MUFiles', 'notification', 'process', $notifyArgs);

    // return result of this operation
    return $result;
}
