<?php
/**
 * MUFiles.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUFiles
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * Notify operation.
 * @param object $entity The treated object.
 * @param array  $params Additional arguments.
 *
 * @return bool False on failure or true if everything worked well.
 */
function MUFiles_operation_notify(&$entity, $params)
{
    $dom = ZLanguage::getModuleDomain('MUFiles');


    // initialise the result flag
    $result = false;

    // workflow parameters are always lower-cased (#656)
    $recipientType = isset($params['recipientType']) ? $params['recipientType'] : $params['recipienttype'];
    
    $notifyArgs = array(
        'recipientType' => $recipientType,
        'action' => $params['action'],
        'entity' => $entity
    );
    
    ModUtil::apiFunc('MUFiles', 'notification', 'process', $notifyArgs);

    // return result of this operation
    return $result;
}
