<?php
/**
 * Files.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\FilesModule\Helper;

use MU\FilesModule\Helper\Base\AbstractViewHelper;

/**
 * Helper implementation class for view layer methods.
 */
class ViewHelper extends AbstractViewHelper
{
   /**
     *
     */
    public static function getMimeType($extension)
    {
        switch ($extension)
        {
            // we have mime types for text documents
            case 'pdf':   //PDF
                $mime = 'application/pdf';
                break;
            case 'doc':  // DOC
                $mime = 'application/msword';
                break;
            case 'docx':  // DOC
                $mime = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
                break;
                
            case 'dotx':  // DOC
                $mime = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
                break;
            case 'odt':  // Libre Office text document
                $mime = 'application/vnd.oasis.opendocument.text';
                break;
            case 'txt': // text file
                $mime = 'text/plain';
                break;
                // we have mime types for tables
            case 'xls': // word excel
                $mime = 'application/msexcel';
                break;
                
            case 'xlsx': // word excel
                $mime = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
                break;
                	
            case 'ppt': // microsoft powerpoint
                $mime = 'application/mspowerpoint';
                break;
            case 'gz':
                $mime = 'application/gzip';
                break;
            case 'zip':
                $mime = 'application/zip';
                break;
            case 'tar':
                $mime = 'application/x-tar';
                break;
        }
        return $mime;
    }
}
