<?php
/**
 * MUFiles.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUFiles
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * This handler class handles the page events of the Form called by the mUFiles_file_edit() function.
 * It aims on the file object type.
 */
class MUFiles_Form_Handler_File_Edit extends MUFiles_Form_Handler_File_Base_Edit
{
    // feel free to extend the base handler class here
}
