<?php
/**
 * MUFiles.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUFiles
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * The mufilesSpecialCollectionMenue plugin provides a special menue of collections.
 *
 * Available parameters:
 *   - collectionId:     Optional id of element as part of unique error message element.
 *   - fileId:
 *   - assign: If set, the results are assigned to the corresponding variable instead of printed out.
 *
 * @param  array            $params All attributes passed to this function from the template.
 * @param  Zikula_Form_View $view   Reference to the view object.
 *
 * @return string The output of the plugin.
 */
function smarty_function_mufilesSpecialCollectionMenue($params, $view)
{
	if ($params['collectionId']) {
        $collectionId = $params['collectionId'];
	} else {
		$collectionId = 0;
	}
	
	if ($params['fileId']) {
		$fileId = $params['fileId'];
	} else {
		$fileId = 0;
	}
	
    $menue = MUFiles_Util_Menue::getCollectionMenue($collectionId ,$fileId);		

    if (array_key_exists('assign', $params)) {
        $view->assign($params['assign'], $menue);

        return;
    }

    return $menue;
}
