<?php
/**
 * MUFiles.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUFiles
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Tue Aug 06 08:44:10 CEST 2013.
 */

/**
 * Abstract object selector plugin implementation class.
 */
abstract class MUFiles_Form_Plugin_AbstractObjectSelector extends MUFiles_Form_Plugin_Base_AbstractObjectSelector
{
    // feel free to add your customisation here
}
