<?php
/**
 * MUFiles.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUFiles
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Abstract object selector plugin implementation class.
 */
abstract class MUFiles_Form_Plugin_AbstractObjectSelector extends MUFiles_Form_Plugin_Base_AbstractObjectSelector
{
    /**
     * Load event handler.
     *
     * @param Zikula_Form_View $view    Reference to Zikula_Form_View object.
     * @param array            &$params Parameters passed from the Smarty plugin function.
     *
     * @return void
     */
    public function load(Zikula_Form_View $view, &$params)
    {
        if (!$this->mandatory) {
            $this->addItem('', NULL);
        }
        if ($this->showEmptyValue != false) {
            $this->addItem('- - -', 0);
        }
    
        $items = $this->loadItems($params);
    
        foreach ($items as $item) {
            if (!$this->isIncluded($item)) {
                continue;
            }
    
            $itemLabel = $this->createItemLabel($item);
            $itemId = $this->createItemIdentifier($item);
            $this->addItem($itemLabel, $itemId);
        }
    }
}
