<?php
/**
 * MUFiles.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUFiles
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * Relation selector plugin implementation class.
 */
class MUFiles_Form_Plugin_RelationSelectorList extends MUFiles_Form_Plugin_Base_RelationSelectorList
{
    // feel free to add your customisation here
}
