<?php
/**
 * MUFiles.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUFiles
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Tue Aug 06 08:44:10 CEST 2013.
 */

/**
 * This class provides object meta data for the Tag module.
 */
class MUFiles_TaggedObjectMeta_MUFiles extends MUFiles_TaggedObjectMeta_Base_MUFiles
{
    // feel free to extend the tag support here
}
