<?php
/**
 * MUFiles.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUFiles
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * Repository class used to implement own convenience methods for performing certain DQL queries.
 *
 * This is the concrete repository class for the many to many relationship
 * between hookobject and collection entities.
 */
class MUFiles_Entity_Repository_HookObjectCollection extends MUFiles_Entity_Repository_Base_HookObjectCollection
{
    // feel free to add your own methods here, like for example reusable DQL queries
}
