<?php
/**
 * Files.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\FilesModule\Form\Type\Hook;

use MU\FilesModule\Form\Type\Hook\Base\AbstractEditFileType;

/**
 * Edit file form type implementation class.
 */
class EditFileType extends AbstractEditFileType
{
    // feel free to extend the base form type class here
}
