<?php
/**
 * Files.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\FilesModule\Form\DataTransformer;

use MU\FilesModule\Form\DataTransformer\Base\AbstractListFieldTransformer;

/**
 * List field transformer implementation class.
 *
 * This data transformer treats multi-valued list fields.
 */
class ListFieldTransformer extends AbstractListFieldTransformer
{
    // feel free to add your customisation here
}
