<?php
/**
 * MUFiles.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUFiles
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Tue Aug 06 08:44:09 CEST 2013.
 */

/**
 * Configuration handler implementation class.
 */
class MUFiles_Form_Handler_Admin_Config extends MUFiles_Form_Handler_Admin_Base_Config
{
    /**
     * Method stub for own additions in subclasses.
     */
    protected function initializeAdditions()
    {
        $maxSize = ModUtil::getVar($this->name, 'maxSize');
        $this->view->assign('maxSize', $maxSize);
        
        return true;
    }
}
