<?php
/**
 * Files.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\FilesModule\HookProvider;

use MU\FilesModule\HookProvider\Base\AbstractFileFormAwareHookProvider;

/**
 * Implementation class for form aware hook provider.
 */
class FileFormAwareHookProvider extends AbstractFileFormAwareHookProvider
{
    // feel free to add your own convenience methods here
}
