<?php
/**
 * Files.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\FilesModule\Validator\Constraints;

use MU\FilesModule\Validator\Constraints\Base\AbstractFileSize;

/**
 * List entry validation constraint.
 *
 * @Annotation
 */
class FileSize extends AbstractFileSize
{
    // here you can customise the constraint
}
