<?php
/**
 * MUFiles.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUFiles
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Generic single item display content plugin implementation class.
 */
class MUFiles_ContentType_Item extends MUFiles_ContentType_Base_Item
{
    // feel free to extend the content type here
}

function MUFiles_Api_ContentTypes_item($args)
{
    return new MUFiles_Api_ContentTypes_itemPlugin();
}
