<?php
/**
 * MUFiles.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUFiles
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Tue Aug 06 08:44:08 CEST 2013.
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the concrete validation class for collection entities.
 */
class MUFiles_Entity_Validator_Collection extends MUFiles_Entity_Validator_Base_Collection
{
    // here you can add custom validation methods or override existing checks
}
