<?php
/**
 * MUFiles.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUFiles
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the concrete validation class for hookobject entities.
 */
class MUFiles_Entity_Validator_Hookobject extends MUFiles_Entity_Validator_Base_Hookobject
{
    // here you can add custom validation methods or override existing checks
}
