<?php
/**
 * Files.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\FilesModule\Form\Type\Finder;

use MU\FilesModule\Form\Type\Finder\Base\AbstractFileFinderType;

/**
 * File finder form type implementation class.
 */
class FileFinderType extends AbstractFileFinderType
{
    // feel free to extend the base form type class here
}
