<?php
/**
 * Files.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\FilesModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use MU\FilesModule\Entity\FileEntity;

/**
 * Event base class for filtering file processing.
 */
class AbstractFilterFileEvent extends Event
{
    /**
     * @var FileEntity Reference to treated entity instance.
     */
    protected $file;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterFileEvent constructor.
     *
     * @param FileEntity $file Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(FileEntity $file, array $entityChangeSet = [])
    {
        $this->file = $file;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return FileEntity
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * Returns the change set.
     *
     * @return array Entity change set
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
