<?php
/**
 * MUFiles.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUFiles
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * This handler class handles the page events of editing forms.
 * It collects common functionality required by different object types.
 */
class MUFiles_Form_Handler_Common_Edit extends MUFiles_Form_Handler_Common_Base_Edit
{
    // feel free to extend the base handler class here
}
