<?php
/**
 * Files.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\FilesModule\Entity\Factory\Base;

use MU\FilesModule\Entity\CollectionEntity;
use MU\FilesModule\Entity\FileEntity;

/**
 * Entity initialiser class used to dynamically apply default values to newly created entities.
 */
abstract class AbstractEntityInitialiser
{
    /**
     * Initialises a given collection instance.
     *
     * @param CollectionEntity $entity The newly created entity instance
     *
     * @return CollectionEntity The updated entity instance
     */
    public function initCollection(CollectionEntity $entity)
    {

        return $entity;
    }

    /**
     * Initialises a given file instance.
     *
     * @param FileEntity $entity The newly created entity instance
     *
     * @return FileEntity The updated entity instance
     */
    public function initFile(FileEntity $entity)
    {

        return $entity;
    }

}
