<?php
/**
 * MUFiles.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUFiles
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * Installer implementation class.
 */
class MUFiles_Installer extends MUFiles_Base_Installer
{
     /**
* Install the MUFiles application.
*
* @return boolean True on success, or false.
*/
    public function install()
    {
        parent::install();
        
        // Set up module hooks
        HookUtil::registerProviderBundles($this->version->getHookProviderBundles()); //TODO next version
        
        return true;
    }
    
    public function uninstall()
    {
        parent::uninstall();
        
        // unregister hook providers
        HookUtil::unregisterProviderBundles($this->version->getHookProviderBundles()); //TODO next version
        return true;
    }
    
        /**
         * Register persistent event handlers.
         * These are listeners for external events of the core and other modules.
         */
        protected function registerPersistentEventHandlers()
        {
    
            parent::registerPersistentEventHandlers();
    
            EventUtil::registerPersistentModuleHandler('MUSound', 'module.scribite.editorhelpers', array('MUSound_Listener_ThirdParty', 'getEditorHelpers'));
            EventUtil::registerPersistentModuleHandler('MUSound', 'moduleplugin.tinymce.externalplugins', array('MUSound_Listener_ThirdParty', 'getTinyMcePlugins'));
            EventUtil::registerPersistentModuleHandler('MUsound', 'moduleplugin.ckeditor.externalplugins', array('MUSound_Listener_ThirdParty', 'getCKEditorPlugins'));
        }
}
