<?php
/**
 * MUFiles.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUFiles
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Validator class for encapsulating common entity validation methods.
 *
 * This is the concrete validation class with general checks.
 */
class MUFiles_Validator extends MUFiles_Base_Validator
{
    // here you can add custom validation methods or override existing checks
}
