src/modules/MUFiles/templates/collection/main.tpl: config/templates/MUFiles/collection/main.tpl
src/modules/MUFiles/templates/collection/view.tpl: config/templates/MUFiles/collection/view.tpl
src/modules/MUFiles/templates/collection/view_quickNav.tpl: config/templates/MUFiles/collection/view_quickNav.tpl
src/modules/MUFiles/templates/collection/view.csv.tpl: config/templates/MUFiles/collection/view.csv.tpl
src/modules/MUFiles/templates/collection/display.tpl: config/templates/MUFiles/collection/display.tpl
src/modules/MUFiles/templates/collection/delete.tpl: config/templates/MUFiles/collection/delete.tpl
src/modules/MUFiles/templates/collection/include_displayItemListOne.tpl: config/templates/MUFiles/collection/include_displayItemListOne.tpl
src/modules/MUFiles/templates/collection/include_displayItemListMany.tpl: config/templates/MUFiles/collection/include_displayItemListMany.tpl
src/modules/MUFiles/templates/file/main.tpl: config/templates/MUFiles/file/main.tpl
src/modules/MUFiles/templates/file/view.tpl: config/templates/MUFiles/file/view.tpl
src/modules/MUFiles/templates/file/view_quickNav.tpl: config/templates/MUFiles/file/view_quickNav.tpl
src/modules/MUFiles/templates/file/view.csv.tpl: config/templates/MUFiles/file/view.csv.tpl
src/modules/MUFiles/templates/file/display.tpl: config/templates/MUFiles/file/display.tpl
src/modules/MUFiles/templates/file/delete.tpl: config/templates/MUFiles/file/delete.tpl
src/modules/MUFiles/templates/file/include_displayItemListOne.tpl: config/templates/MUFiles/file/include_displayItemListOne.tpl
src/modules/MUFiles/templates/file/include_displayItemListMany.tpl: config/templates/MUFiles/file/include_displayItemListMany.tpl
src/modules/MUFiles/templates/hookobject/main.tpl: config/templates/MUFiles/hookobject/main.tpl
src/modules/MUFiles/templates/hookobject/view.tpl: config/templates/MUFiles/hookobject/view.tpl
src/modules/MUFiles/templates/hookobject/view_quickNav.tpl: config/templates/MUFiles/hookobject/view_quickNav.tpl
src/modules/MUFiles/templates/hookobject/view.csv.tpl: config/templates/MUFiles/hookobject/view.csv.tpl
src/modules/MUFiles/templates/hookobject/display.tpl: config/templates/MUFiles/hookobject/display.tpl
src/modules/MUFiles/templates/hookobject/delete.tpl: config/templates/MUFiles/hookobject/delete.tpl
src/modules/MUFiles/templates/hookobject/include_displayItemListOne.tpl: config/templates/MUFiles/hookobject/include_displayItemListOne.tpl
src/modules/MUFiles/templates/hookobject/include_displayItemListMany.tpl: config/templates/MUFiles/hookobject/include_displayItemListMany.tpl
src/modules/MUFiles/templates/admin/header.tpl: config/templates/MUFiles/admin/header.tpl
src/modules/MUFiles/templates/admin/footer.tpl: config/templates/MUFiles/admin/footer.tpl
src/modules/MUFiles/templates/user/header.tpl: config/templates/MUFiles/user/header.tpl
src/modules/MUFiles/templates/user/footer.tpl: config/templates/MUFiles/user/footer.tpl
src/modules/MUFiles/templates/admin/inlineRedirectHandler.tpl: config/templates/MUFiles/admin/inlineRedirectHandler.tpl
src/modules/MUFiles/templates/user/inlineRedirectHandler.tpl: config/templates/MUFiles/user/inlineRedirectHandler.tpl
src/modules/MUFiles/templates/collection/edit.tpl: config/templates/MUFiles/collection/edit.tpl
src/modules/MUFiles/templates/collection/inlineRedirectHandler.tpl: config/templates/MUFiles/collection/inlineRedirectHandler.tpl
src/modules/MUFiles/templates/file/edit.tpl: config/templates/MUFiles/file/edit.tpl
src/modules/MUFiles/templates/file/inlineRedirectHandler.tpl: config/templates/MUFiles/file/inlineRedirectHandler.tpl
src/modules/MUFiles/templates/hookobject/edit.tpl: config/templates/MUFiles/hookobject/edit.tpl
src/modules/MUFiles/templates/hookobject/inlineRedirectHandler.tpl: config/templates/MUFiles/hookobject/inlineRedirectHandler.tpl
src/modules/MUFiles/templates/helper/include_categories_display.tpl: config/templates/MUFiles/helper/include_categories_display.tpl
src/modules/MUFiles/templates/helper/include_categories_edit.tpl: config/templates/MUFiles/helper/include_categories_edit.tpl
src/modules/MUFiles/templates/helper/include_standardfields_display.tpl: config/templates/MUFiles/helper/include_standardfields_display.tpl
src/modules/MUFiles/templates/helper/include_standardfields_edit.tpl: config/templates/MUFiles/helper/include_standardfields_edit.tpl
src/modules/MUFiles/templates/admin/config.tpl: config/templates/MUFiles/admin/config.tpl
src/modules/MUFiles/templates/email/notifycollectionCreator.tpl: config/templates/MUFiles/email/notifycollectionCreator.tpl
src/modules/MUFiles/templates/email/notifycollectionModerator.tpl: config/templates/MUFiles/email/notifycollectionModerator.tpl
src/modules/MUFiles/templates/email/notifyfileCreator.tpl: config/templates/MUFiles/email/notifyfileCreator.tpl
src/modules/MUFiles/templates/email/notifyfileModerator.tpl: config/templates/MUFiles/email/notifyfileModerator.tpl
src/modules/MUFiles/templates/include_pdfheader.tpl: config/templates/MUFiles/include_pdfheader.tpl
