services:
    mu_files_module.app_settings:
        class: MU\FilesModule\AppSettings
        arguments:
            - "@zikula_extensions_module.api.variable"
            - "@zikula_groups_module.group_repository"
