services:
    # Form field types
    
    mu_files_module.form.type.field.multilist:
        class: MU\FilesModule\Form\Type\Field\MultiListType
        arguments:
            - "@mu_files_module.listentries_helper"
        tags: ['form.type']
    
    mu_files_module.form.type.field.upload:
        class: MU\FilesModule\Form\Type\Field\UploadType
        arguments:
            - "@translator.default"
            - "@mu_files_module.image_helper"
            - "@mu_files_module.upload_helper"
        tags: ['form.type']
