services:
    mu_files_module.link_container:
        class: MU\FilesModule\Container\LinkContainer
        arguments:
            - "@translator.default"
            - "@router"
            - "@zikula_extensions_module.api.variable"
            - "@mu_news_module.controller_helper"
            - "@mu_news_module.permission_helper"
        tags:
            - { name: zikula.link_container }
