<?php
/**
 * Files.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\FilesModule\Entity;

use MU\FilesModule\Entity\Base\AbstractHookAssignmentEntity;

/**
 * Entity implementation class for hooked object assignments.
 *
 * @ORM\Table(name="mu_files_hookassignment")
 */
class HookAssignmentEntity extends AbstractHookAssignmentEntity
{
    // feel free to add your own methods here
}
