<?php
/**
 * MUFiles.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUFiles
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * Utility implementation class for list field entries related methods.
 */
class MUFiles_Util_ListEntries extends MUFiles_Util_Base_ListEntries
{
    // feel free to add your own convenience methods here
}
