<?php
/**
 * MUFiles.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUFiles
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Tue Aug 06 08:44:09 CEST 2013.
 */

/**
 * This is the Ajax controller class providing navigation and interaction functionality.
 */
class MUFiles_Controller_Ajax extends MUFiles_Controller_Base_Ajax
{
    // feel free to add your own controller methods here
}
