<?php
/**
 * MUFiles.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUFiles
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * Collection controller class providing navigation and interaction functionality.
 */
class MUFiles_Controller_Collection extends MUFiles_Controller_Base_Collection
{
    // feel free to add your own controller methods here
}
